-- ============================================================
-- 007 — Students, guardians and relationship tables
-- ============================================================

CREATE TABLE students (
  id                             uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id                      uuid        NOT NULL REFERENCES tenants (id),
  -- Simple incrementing integer per tenant.
  -- Generated by calling public.next_student_number(tenant_id) at insert time.
  student_number                 integer     NOT NULL,
  first_name                     text        NOT NULL,
  last_name                      text        NOT NULL,
  date_of_birth                  date,
  gender                         text,
  email                          text,
  phone                          text,
  address                        text,
  school_id                      uuid        REFERENCES schools (id),
  status                         text        NOT NULL DEFAULT 'active',
  -- Embedded emergency contact fields — populated only when the emergency
  -- contact is NOT a registered guardian. When a guardian is the emergency
  -- contact, set student_guardians.is_emergency_contact = true instead.
  emergency_contact_name         text,
  emergency_contact_phone        text,
  emergency_contact_relationship text,
  notes                          text,
  created_at                     timestamptz NOT NULL DEFAULT now(),
  updated_at                     timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT students_tenant_number_key UNIQUE (tenant_id, student_number)
);

CREATE TABLE guardians (
  id         uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id  uuid        NOT NULL REFERENCES tenants (id),
  first_name text        NOT NULL,
  last_name  text        NOT NULL,
  email      text,
  phone      text,
  address    text,
  occupation text,
  notes      text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- Links students to their guardians with per-link relationship metadata.
CREATE TABLE student_guardians (
  id                   uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id            uuid        NOT NULL REFERENCES tenants   (id),
  student_id           uuid        NOT NULL REFERENCES students  (id) ON DELETE CASCADE,
  guardian_id          uuid        NOT NULL REFERENCES guardians (id) ON DELETE CASCADE,
  -- Textual relationship, e.g. 'mother', 'father', 'grandparent', 'carer'
  relationship         text        NOT NULL,
  is_primary           boolean     NOT NULL DEFAULT false,
  -- True when this guardian is the student's designated emergency contact.
  -- Mutually exclusive with the students.emergency_contact_* columns:
  -- use one mechanism or the other, not both.
  is_emergency_contact boolean     NOT NULL DEFAULT false,
  can_pickup           boolean     NOT NULL DEFAULT true,
  created_at           timestamptz NOT NULL DEFAULT now(),
  updated_at           timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT student_guardians_pair_key UNIQUE (student_id, guardian_id)
);

-- Co-parent relationship between two guardians.
-- Canonical pair: guardian_a_id < guardian_b_id (UUID lexicographic order).
-- This ordering is enforced at the application layer before insert —
-- not as a DB CHECK to keep UUID arithmetic out of the schema.
CREATE TABLE guardian_co_parent_links (
  id            uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id     uuid        NOT NULL REFERENCES tenants   (id),
  guardian_a_id uuid        NOT NULL REFERENCES guardians (id),
  guardian_b_id uuid        NOT NULL REFERENCES guardians (id),
  status        text        NOT NULL DEFAULT 'pending',
  -- Populated when the second guardian confirms the co-parent link
  confirmed_at  timestamptz,
  created_at    timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT guardian_co_parent_links_pair_key    UNIQUE (guardian_a_id, guardian_b_id),
  CONSTRAINT guardian_co_parent_links_status_check CHECK  (status IN ('pending', 'confirmed'))
);

-- Sibling relationship between two students.
-- Canonical pair: student_a_id < student_b_id enforced at application layer.
-- Rows are auto-created by application logic when a co-parent link is
-- confirmed and both guardians appear on the respective students.
CREATE TABLE sibling_links (
  id           uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id    uuid        NOT NULL REFERENCES tenants  (id),
  student_a_id uuid        NOT NULL REFERENCES students (id),
  student_b_id uuid        NOT NULL REFERENCES students (id),
  created_at   timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT sibling_links_pair_key UNIQUE (student_a_id, student_b_id)
);

ALTER TABLE students                 ENABLE ROW LEVEL SECURITY;
ALTER TABLE guardians                ENABLE ROW LEVEL SECURITY;
ALTER TABLE student_guardians        ENABLE ROW LEVEL SECURITY;
ALTER TABLE guardian_co_parent_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE sibling_links            ENABLE ROW LEVEL SECURITY;

CREATE INDEX idx_students_tenant_id                     ON students (tenant_id);
CREATE INDEX idx_students_school_id                     ON students (school_id);
CREATE INDEX idx_guardians_tenant_id                    ON guardians (tenant_id);
CREATE INDEX idx_student_guardians_tenant_id            ON student_guardians (tenant_id);
CREATE INDEX idx_student_guardians_student_id           ON student_guardians (student_id);
CREATE INDEX idx_student_guardians_guardian_id          ON student_guardians (guardian_id);
CREATE INDEX idx_guardian_co_parent_links_tenant_id     ON guardian_co_parent_links (tenant_id);
CREATE INDEX idx_guardian_co_parent_links_guardian_a    ON guardian_co_parent_links (guardian_a_id);
CREATE INDEX idx_guardian_co_parent_links_guardian_b    ON guardian_co_parent_links (guardian_b_id);
CREATE INDEX idx_sibling_links_tenant_id                ON sibling_links (tenant_id);
CREATE INDEX idx_sibling_links_student_a                ON sibling_links (student_a_id);
CREATE INDEX idx_sibling_links_student_b                ON sibling_links (student_b_id);

-- Enforce at most one primary guardian per student at the DB level
CREATE UNIQUE INDEX student_guardians_one_primary_per_student
  ON student_guardians (student_id)
  WHERE is_primary = true;
